apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: taman9333/foo
      context: foo
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'index.js'
            dest: .
    - image: taman9333/bar
      context: bar
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'index.js'
            dest: .
    - image: taman9333/baz
      context: baz
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'index.js'
            dest: .
    - image: taman9333/xyz
      context: xyz
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'main.go'
            dest: .
          - src: './**/*.go'
            dest: .
